ARG FN_NAME
ARG COMMAND

FROM $FN_NAME
ARG COMMAND
RUN rm -rf /criu
RUN mkdir /criu
RUN mkdir /criu/checkpoint
RUN echo 0 > /criu/restore_flag
COPY tools/__criu.sh /criu/__criu.sh
RUN /criu/__criu.sh $COMMAND
